config/routes.rb
PongLords::Application.routes.draw do
  api_version(module: "Api::V1", path: {:value => "v1"}, defaults: {:format => "json"}) do
    resources :players, only: [:index, :show, :create]
    resources :invitations, only: [:create]
    resources :matches, only: [:create]

    post :sign_in, to: 'sessions#create', as: :sign_in
  end

  devise_for :players

  get '/players/:uuid/claim', to: 'players#new', as: 'invited_player_registration'
  post '/players', to: 'players#create', as: 'player_invitation_claim'

  get 'thanks', to: 'static#thanks'

  root to: "home#index"
end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  before_validation :set_uuid
  after_create :send_invitation_email

  validates_presence_of :uuid
  validates_presence_of :email
  validates_presence_of :first_name
  validates_presence_of :last_name

  validates_uniqueness_of :email
  validates_uniqueness_of :uuid

  private

  def set_uuid
    return unless self.uuid.blank?
    self.uuid = UUID.new.generate
  end

  def send_invitation_email
    InvitationMailer.invite_player(self).deliver
  end
end

app/models/match.rb
class Match < ActiveRecord::Base
  after_save :update_player_rankings

  has_many :results
  has_many :players, through: :results

  validate :player_count

  private

  def update_player_rankings
    results.each do |result|
      RankingCalculator.new(result, results.where(won: !result.won?).map(&:player), result.won?).update_ranking
      DiversityIndexCalculator.new(result.player).update_points
      EloWithDiversityIndexCalculator.new(result.player, result.player.ranking, result.player.diversity_index).update_score
    end
  end

  def player_count
    count = results.map(&:player).count
    errors.add(:base, "Invalid number of players") unless count == 2 || count == 4

    win_count = results.select(&:won).count
    loss_count = results.reject(&:won).count
    errors.add(:base, "Number of winners do not match the number of losers") unless win_count == loss_count
  end
end

app/models/player.rb
class Player < ActiveRecord::Base
  PRO_RANKING = 2400
  STARTER_BOUNDRY = 5
  DEFAULT_RANKING = 1000

  devise :database_authenticatable, :recoverable,
         :rememberable, :trackable, :validatable,
         :token_authenticatable, :lockable

  has_many :results
  has_many :matches, through: :results

  scope :by_name, -> { order(:name) }
  scope :by_ranking, -> { order("ranking DESC") }
  scope :by_elo_with_diversity_index, -> { order("elo_with_diversity_index DESC") }
  scope :with_games, -> { joins(:results).where("players.id = results.player_id").distinct }

  def wins
    outcome_count(true)
  end

  def losses
    outcome_count(false)
  end

  private

  def outcome_count(win)
    results.where(won: win).count
  end
end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :match
  belongs_to :player
  belongs_to :doubles_partner, class_name: "Player"

  validates_uniqueness_of :player_id, scope: :match_id
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  protect_from_forgery with: :null_session
end

app/controllers/api/v1/invitations_controller.rb
class Api::V1::InvitationsController < Api::V1::BaseController
  def create
    @invitation = Invitation.new(invitation_params)
    if @invitation.save
      render :show
    else
      render json: { errors: @invitation.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def invitation_params
    params.require(:invitation).permit(:email, :first_name, :last_name)
  end
end

app/controllers/api/v1/matches_controller.rb
class Api::V1::MatchesController < Api::V1::BaseController
  def create
    match = Match.new

    players = []
    params[:match][:players].each do |player|
      match.results.build(player: Player.find(player[:id]), won: player[:won])
    end

    match.results.each do |result|
      result.doubles_partner = match.results.select { |res| res.won == result.won }
                                            .reject { |res| res.player_id == result.player_id }
                                            .first.try(:player)
    end

    if match.save
      @players = match.players
      render :show
    else
      render json: { errors: match.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def match_params
    params.require(:match).permit(:players)
  end
end

app/controllers/api/v1/players_controller.rb
class Api::V1::PlayersController < Api::V1::BaseController
  BATCH_SIZE = 20

  def index
    if params[:search]
      term = "%#{params[:search]}%"
      @players = Player.where("first_name ILIKE ? OR
                               last_name ILIKE ? OR
                               email ILIKE ? OR
                               nickname ILIKE ?", term, term, term, term)
    else
      @players = Player.order("created_at DESC").take(BATCH_SIZE)
    end
  end

  def show
    @player = Player.find(params[:id])
  end

  def create
    @player = Player.new(player_params)
    if @player.save
      render :show
    else
      render json: { errors: @player.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def player_params
    params.require(:player).permit(:email, :first_name, :last_name, :nickname, :password, :password_confirmation)
  end
end

app/controllers/api/v1/sessions_controller.rb
class Api::V1::SessionsController < Api::V1::BaseController

  before_filter :ensure_params_present, only: [:create]

  def create
    @player = Player.find_for_database_authentication(email: params[:player][:email])
    return invalid_authentication_attempt unless @player

    if @player.valid_password?(params[:player][:password])
      @player.ensure_authentication_token!
      return successful_authentication
    end

    invalid_authentication_attempt
  end

  private

  def ensure_params_present
    return unless params[:player].blank? || params[:player][:email].blank? || params[:player][:password].blank?
    render json: { errors: "Missing required parameters" }, status: :unprocessable_entity
  end

  def invalid_authentication_attempt
    render json: { errors: "The email and or password are not valid" }, status: :unauthorized
  end

  def successful_authentication
    render 'api/v1/players/show'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def new
    invitation = Invitation.find_by_uuid(params[:uuid]) || not_found
    @player = Player.new(email: invitation.email,
                         first_name: invitation.first_name,
                         last_name: invitation.last_name)
  end

  def create
    @player = Player.new(player_params)

    if @player.save
      redirect_to thanks_path
    else
      render :new
    end
  end

  private

  def player_params
    params.require(:player).permit(:email, :password, :password_confirmation, :first_name, :last_name, :nickname)
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.slim
.centered-ctn
	.img-ctn
	  = image_tag "logo.png"

app/views/layouts/application.html.slim
doctype html
html
head
  title PongLords
  = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
  = javascript_include_tag "application", "data-turbolinks-track" => true
  = csrf_meta_tags
  meta name="viewport" content="width=device-width"
body.red-bg
  - if notice
    p.notice
      = notice
  - if alert
    p.alert
      = alert
  = yield

app/views/players/new.html.slim
.container

  = simple_form_for(@player, :url => player_invitation_claim_path(@player), html: { class: 'centered-ctn'}) do |f|
    .img-ctn
      = image_tag "logo.png"
    .img-ctn
      = image_tag "join_pong_lords.png"

    = f.full_error :email
    = f.input :email, :required => true, label: false, placeholder: "Email", error: false
    = f.full_error :first_name
    = f.input :first_name, :required => true, label: false, placeholder: "First name", error: false
    = f.full_error :last_name
    = f.input :last_name, :required => true, label: false, placeholder: "Last name", error: false
    = f.full_error :nickname
    = f.input :nickname, :autofocus => true, label: false, placeholder: "Handle (optional)", error: false
    = f.full_error :password
    = f.input :password, :required => true, label: false, placeholder: "Password", error: false
    = f.full_error :password_confirmation
    = f.input :password_confirmation, :required => true, label: false, placeholder: "Confirm password", error: false

    .input
      = f.button :submit, "submit", class: "submit-btn"

app/views/players/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>